server: 
   port: 9527 
   
spring: 
   application: 
      name: microservicecloud-zuul-gateway 
      
eureka: 
   client: 
      service-url: 
         defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
   instance: 
      instance-id: gateway-9527.com 
      prefer-ip-address: true
      
# 代理名称
zuul: 
   # ignore-services: microservicecloud-dept    #设置原路由不可访问
   prefix: /atguigu           #http://myzuul.com:9527/atguigu/mydept/get/1
   ignore-services: "*"      #设置所有路由不可访问，仅有 path 里面的才可以
   routes: 
      mydept.serviceId: microservicecloud-dept 
      mydept.path: /mydept/**   
info: 
   app.name: atguigu-microcloud 
   company.name: www.atguigu.com 
   build.artifactId: microservicecloud-zuul-gateway-952
   build.version: 0.0.1-SNAPSHOT 
         
         