server: 
   port: 3344

spring: 
   application:
      name: microservicecloud-config
   cloud: 
      config: 
         server:
            git: 
               url: git@git......   #GitHub上面的地址